policy:
  type: smolvla
  device: cuda
  use_lora: true
  lora_config:
    r: 8
    lora_alpha: 16
    lora_dropout: 0.05
    bias: "none"
    task_type: "CAUSAL_LM"
    # target_modules: ["q_proj", "v_proj"]  # Uncomment and set as needed for your model

batch_size: 2
num_workers: 0
steps: 2
seed: 42
output_dir: ./lora_test_output
log_freq: 1
save_freq: 2
eval_freq: 0
save_checkpoint: false

# Add other required config fields as needed for your environment/dataset